In [2]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [5]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [6]:
#can cast a list of lists to generate an array

In [9]:
#but there are fast ways to generate arrays
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros((4,5)) #for some reason zeros() takes a touple as inputs

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(4,5)

array([[0.8727261 , 0.94908477, 0.36967172, 0.77905863, 0.27843255],
       [0.51589914, 0.83373685, 0.49328646, 0.41554308, 0.38257061],
       [0.56824137, 0.27296976, 0.7397668 , 0.94584976, 0.28935661],
       [0.66254318, 0.71766969, 0.29516926, 0.49361809, 0.63600731]])

In [19]:
np.random.randn(2) #standard normal dist around zero

array([ 0.36889878, -0.33975223])

In [21]:
np.random.randint(3,47) #rand ints between the two values with the first value included and the second value excluded

45

In [27]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)
ranarr

array([49, 29, 23, 31,  0, 18, 10, 42, 16, 45])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

49

In [33]:
ranarr.argmax()

0

In [34]:
arr.shape

(25,)

In [35]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [37]:
from numpy.random import randint

In [38]:
randint(2,10)

3

In [2]:
#5.20 Numpy array indexing

In [4]:
arr = np.arange(0,11)

In [6]:
#slice notation: starting index and stop index
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
#grab everything beyong 5. But not including position 5.
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
#or yo ucan broadcast on an array
slice_arr[:] = 99

In [13]:
#NOTE that slice_arr is a just a view of arr. The data is not actually copied. Changing one changes the other. 
print(slice_arr)
print(arr)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [14]:
#how to make a copy?
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:] = 100

In [16]:
print(arr_copy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99 99  6  7  8  9 10]


In [20]:
#indexing a 2D array (matrix)
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [21]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d[0][0]

5

In [23]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[:,2]

array([15, 30, 45])

In [28]:
arr_2d[2,1] #row then column

40

In [ ]:
#using boolean operaters to filter arrays

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
bool_arr = arr > 5

In [35]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [36]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [37]:
#Numpy Operations

In [38]:
arr = np.arange(0,11)

In [39]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [41]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [44]:
arr/arr #dividing by zero yeilds nan but code runs


C:\Users\Jake\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
#universal array functions (ufunc)

In [46]:
np.sqrt(arr) #exp, max, sin, log, 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])